//*******************************************************************************/
//*										*/
//*	『インフィニティ』							*/
//*										*/
//*		【タイトルデータ】						*/
//*			担当：							*/
//*										*/
//*				(有)レジスタ					*/
//*******************************************************************************/
///ABCDE DCBAE
var TTLTB	= {
    "TITLE_PR_01":"プロローグ,天国はここにある",
    "TITLE_PR_02":"プロローグ,αでありωである",
    "TITLE_PR_03":"プロローグ,フォール／ダウン",
    "TITLE_CO1_01":"ココロ編,母性の懐で",
    "TITLE_CO1_02":"ココロ編,閉鎖された構造状態",
    "TITLE_CO1_03":"ココロ編,精神の『少女』",
    "TITLE_CO1_04":"ココロ編,小児期と思春期の行為障害",
    "TITLE_CO1_05":"ココロ編,主よ。大いなるセフィロトよ",
    "TITLE_CO1_06":"ココロ編,自我の解放",
    "TITLE_CO1_07":"ココロ編,小児期と思春期の人格形成",
    "TITLE_CO1_08":"ココロ編,アニマの中のアニムス",
    "TITLE_CO1_09":"ココロ編,逃避できない現実",
    "TITLE_CO1_10":"ココロ編,自閉的状況に陥る瞬間",
    "TITLE_CO1_11":"ココロ編,こころと体と鎮静剤",
    "TITLE_CO1_12":"ココロ編,病的解離における症状集団",
    "TITLE_CO1_13":"ココロ編,衣服の乱れたアリス",
    "TITLE_CO2_01":"ココロ編,男性と女性の基本的な違い",
    "TITLE_CO2_02":"ココロ編,朝ご飯はカラダにとっても重要",
    "TITLE_CO2_03":"ココロ編,相互理解とは？",
    "TITLE_CO2_04":"ココロ編,原因と理由",
    "TITLE_CO2_05":"ココロ編,信頼と欺き",
    "TITLE_CO2_06":"ココロ編,異状事態警報発令！？",
    "TITLE_CO2_07":"ココロ編,初原の海の味",
    "TITLE_CO2_08":"ココロ編,集団意識の軋轢",
    "TITLE_CO2_09":"ココロ編,傷痕は疑心暗鬼の味",
    "TITLE_CO2_10":"ココロ編,至福の在る場所",
    "TITLE_CO2_11":"ココロ編,わたしはここにいるよ",
    "TITLE_CO2_12":"ココロ編,偽りの影",
    "TITLE_CO3_01":"ココロ編,変わろうとする欲求",
    "TITLE_CO3_02":"ココロ編,ヒトとココロ",
    "TITLE_CO3_03":"ココロ編,生きる意味、そして決断",
    "TITLE_CO3_04":"ココロ編,彼女の病状",
    "TITLE_CO3_05":"ココロ編,『運命』って信じますか？",
    "TITLE_CO3_06":"ココロ編,或る精神鑑定の結果",
    "TITLE_CO3_07":"ココロ編,依存できるもの",
    "TITLE_CO3_08":"ココロ編,鎖状の螺旋",
    "TITLE_CO3_09":"ココロ編,記憶と思惑",
    "TITLE_CO3_10":"ココロ編,新たなる生命",
    "TITLE_CO4_01":"ココロ編,磔られた心的外傷",
    "TITLE_CO4_02":"ココロ編,信じる気持ち",
    "TITLE_CO4_03":"ココロ編,造られた人格交換",
    "TITLE_CO4_04":"ココロ編,自我崩壊の始まり",
    "TITLE_CO4_05":"ココロ編,命の選択",
    "TITLE_CO4_06":"ココロ編,白い世界",
    "TITLE_CO4_07":"ココロ編,不安と神経衰弱の狭間で",
    "TITLE_CO4_08":"ココロ編,ＤＩＤ発現",
    "TITLE_CO4_09":"ココロ編,絶望の深淵・Ⅰ",
    "TITLE_CO5_01":"ココロ編,一握の安息",
    "TITLE_CO5_02":"ココロ編,私欲の果てに……",
    "TITLE_CO5_03":"ココロ編,私怨の果てに……",
    "TITLE_CO5_04":"ココロ編,私案の果てに……",
    "TITLE_CO5_05":"ココロ編,怯える存在、怯えられる存在",
    "TITLE_CO5_06":"ココロ編,正当防衛あるいは冤罪",
    "TITLE_CO5_07":"ココロ編,残酷な団欒",
    "TITLE_CO5_08":"ココロ編,母と子と",
    "TITLE_CO5_09":"ココロ編,最後に訪れた希望を",
    "TITLE_CO5_10":"ココロ編,終わりのない遮蔽環境",
    "TITLE_CO5_11":"ココロ編,自己犠牲の結末",
    "TITLE_CO5_12":"ココロ編,消える灯火",
    "TITLE_CO5_13":"ココロ編,祝福に迎えられながら",
    "TITLE_CO6_01":"ココロ編,せめてもの幸福",
    "TITLE_CO6_02":"ココロ編,永遠の少年",
    "TITLE_CO6_03":"ココロ編,人が作りし奇蹟",
    "TITLE_CO6_04":"ココロ編,吐露される本音",
    "TITLE_CO6_05":"ココロ編,闇に舞い降りる天使",
    "TITLE_CO7_01":"ココロ編,終局への抗い",
    "TITLE_CO7_02":"ココロ編,希望の扉は叩かれた",
    "TITLE_CO7_03":"ココロ編,いつか還るべき約束の場所へ",
    "TITLE_CO7_04":"ココロ編,定められた運命",
    "TITLE_CO7_05":"ココロ編,生きられなかった影",
    "TITLE_CO7_06":"ココロ編,新世界に神は降り立つ",
    "TITLE_CO7_07":"ココロ編,絶望の深淵・Ⅱ",
    "TITLE_COEP_01":"ココロ編,籠の中の．．．",
    "TITLE_SA1_01":"サトル編,Prenatal",
    "TITLE_SA1_02":"サトル編,Persona",
    "TITLE_SA1_03":"サトル編,Animus",
    "TITLE_SA1_04":"サトル編,Trick Star",
    "TITLE_SA1_05":"サトル編,Shadow",
    "TITLE_SA1_06":"サトル編,Great Mother",
    "TITLE_SA1_07":"サトル編,Separation",
    "TITLE_SA1_08":"サトル編,Uniform",
    "TITLE_SA1_09":"サトル編,Dimly",
    "TITLE_SA2_01":"サトル編,Calmness",
    "TITLE_SA2_02":"サトル編,Examine",
    "TITLE_SA2_03":"サトル編,Break−Time",
    "TITLE_SA2_04":"サトル編,Mind−Education",
    "TITLE_SA2_05":"サトル編,Transmit",
    "TITLE_SA2_06":"サトル編,Virgin−Ceiling",
    "TITLE_SA2_07":"サトル編,Miserable",
    "TITLE_SA2_08":"サトル編,Reflection･Ⅰ",
    "TITLE_SA2_09":"サトル編,Polyhedron",
    "TITLE_SA2_10":"サトル編,Old Wise Man",
    "TITLE_SA2_11":"サトル編,Seized",
    "TITLE_SA2_12":"サトル編,Receive",
    "TITLE_SA2_13":"サトル編,Reflection･Ⅱ",
    "TITLE_SA2_14":"サトル編,Crucify's Rat",
    "TITLE_SA2_15":"サトル編,Requiem",
    "TITLE_SA3_01":"サトル編,Respite",
    "TITLE_SA3_02":"サトル編,D−H−A!!",
    "TITLE_SA3_15":"サトル編,N−B−A??",
    "TITLE_SA3_03":"サトル編,Piece Of Cheese",
    "TITLE_SA3_04":"サトル編,Dying",
    "TITLE_SA3_05":"サトル編,Dependence",
    "TITLE_SA3_06":"サトル編,Fibber?",
    "TITLE_SA3_07":"サトル編,Sabbath Time",
    "TITLE_SA3_08":"サトル編,Ayahuasca Matter",
    "TITLE_SA3_09":"サトル編,Pregnant Girl",
    "TITLE_SA3_10":"サトル編,Star's Prince",
    "TITLE_SA3_11":"サトル編,Heteronomie",
    "TITLE_SA3_12":"サトル編,Isomorphism",
    "TITLE_SA3_13":"サトル編,Liberation",
    "TITLE_SA3_14":"サトル編,TORAUMA",
    "TITLE_SA4_01":"サトル編,Nucleotide",
    "TITLE_SA4_02":"サトル編,Fitful",
    "TITLE_SA4_03":"サトル編,Jesting",
    "TITLE_SA4_04":"サトル編,Puer Aeternus",
    "TITLE_SA4_05":"サトル編,Awakening",
    "TITLE_SA4_06":"サトル編,Transference",
    "TITLE_SA4_07":"サトル編,Real",
    "TITLE_SA4_08":"サトル編,Trinity",
    "TITLE_SA4_09":"サトル編,Quantum Teleportation",
    "TITLE_SA4_10":"サトル編,Destruction",
    "TITLE_SA4_11":"サトル編,Insanity",
    "TITLE_SA4_12":"サトル編,Fatal",
    "TITLE_SA4_13":"サトル編,Disclose",
    "TITLE_SA5_01":"サトル編,Lethal",
    "TITLE_SA5_02":"サトル編,Antidote",
    "TITLE_SA5_03":"サトル編,Miracle Child",
    "TITLE_SA5_04":"サトル編,Recollect",
    "TITLE_SA5_05":"サトル編,Phobia",
    "TITLE_SA5_06":"サトル編,Insertion",
    "TITLE_SA5_07":"サトル編,Promise",
    "TITLE_SA5_08":"サトル編,Hekate",
    "TITLE_SA5_09":"サトル編,Unmask",
    "TITLE_SA6_01":"サトル編,Another Shadow",
    "TITLE_SA6_02":"サトル編,Rejection",
    "TITLE_SA6_03":"サトル編,Revenger",
    "TITLE_SA6_04":"サトル編,Old Wise Woman",
    "TITLE_SA6_05":"サトル編,Research",
    "TITLE_SA7_01":"サトル編,Consciousness",
    "TITLE_SA7_02":"サトル編,Symbolic",
    "TITLE_SA7_03":"サトル編,The Third Area",
    "TITLE_SA7_04":"サトル編,Apoptosis",
    "TITLE_SA7_05":"サトル編,Ambivalence",
    "TITLE_SA7_06":"サトル編,The End Of World",
    "TITLE_SA7_07":"サトル編,The End Of Mind",
    "TITLE_SA7_08":"サトル編,Identification",
    "TITLE_SA7_09":"サトル編,Anima",
    "TITLE_SAEP_01":"サトル編,Delta",
    "TITLE_SAEP_02":"サトル編,Infinite History",
    "TITLE_SAEP_03":"サトル編,Never More",
    "TITLE_SAEP_04":"サトル編,Ever More",
    "TITLE_SAEP_05":"サトル編,More Remember",
    "TITLE_SAEP_06":"サトル編,Where Is “Self”?",
};

