// フラグの解放だけっぽ
function Command_R11_EXIT(){
    var _data = MacroData[DDMode][MacroNum][1].split(",");
    MacroData2	= null;
    MacroData2	= new Array();
    MacroNum2	= 0;
    MacroMax2	= 0;
    Macro2Flag	= true;
    
    RegData["SF_GAME_CLEAR"]	= 1;	//     RSET		SF_GAME_CLEAR, 1
//    LOCAL		ED_SHORTCUT
//    LOCAL		ED_SHORTCUT1
//    LOCAL		ED_SHORTCUT2
//    LOCAL		ED_COUNT
//    LOCAL		ED_COUNT1
//    LOCAL		ED_COUNT2
//    LOCAL		ED_OMAKE
    RegData["SR_LIN"]	= RegData["LR_LIN"];	// RSET	SR_LIN,LR_LIN
    RegData["SR_COCORO_ILLUST"]	= RegData["LR_COCORO_ILLUST"];	// RSET	SR_COCORO_ILLUST,LR_COCORO_ILLUST
    RegData["SR_COCORO_MAGURO"]	= RegData["LF_COCORO_MAGURO"];	// RSET	SR_COCORO_MAGURO,LF_COCORO_MAGURO
    RegData["SR_COCORO_HUTAGO"]	= RegData["LF_COCORO_HUTAGO"];	// RSET	SR_COCORO_HUTAGO,LF_COCORO_HUTAGO
    RegData["SR_COCORO_KANRI_COCORO"]	= RegData["LF_COCORO_KANRI_COCORO"];	// RSET	SR_COCORO_KANRI_COCORO,LF_COCORO_KANRI_COCORO
    RegData["SR_SATORU_NAYAMU"]	= RegData["LF_SATORU_NAYAMU"];	// RSET	SR_SATORU_NAYAMU,LF_SATORU_NAYAMU
    RegData["SR_SATORU_COFFEE"]	= RegData["LF_SATORU_COFFEE"];	// RSET	SR_SATORU_COFFEE,LF_SATORU_COFFEE
    RegData["SR_SATORU_COCORO_LIVE"]	= RegData["LF_SATORU_COCORO_LIVE"];	// RSET	SR_SATORU_COCORO_LIVE,LF_SATORU_COCORO_LIVE
    RegData["SR_SATORU_GURUGURU"]	= RegData["LF_SATORU_GURUGURU"];	// RSET	SR_SATORU_GURUGURU,LF_SATORU_GURUGURU
    RegData["SR_BAD_COCORO_SUIMINYAKU"]	= RegData["LF_BAD_COCORO_SUIMINYAKU"];	// RSET	SR_BAD_COCORO_SUIMINYAKU,LF_BAD_COCORO_SUIMINYAKU
    RegData["SR_BAD_COCORO_SYOKUJI"]	= RegData["LF_BAD_COCORO_SYOKUJI"];	// RSET	SR_BAD_COCORO_SYOKUJI,LF_BAD_COCORO_SYOKUJI
    RegData["SR_BAD_COCORO_ENOMOTO"]	= RegData["LF_BAD_COCORO_ENOMOTO"];	// RSET	SR_BAD_COCORO_ENOMOTO,LF_BAD_COCORO_ENOMOTO
    RegData["SR_BAD_COCORO_SPHIA"]	= RegData["LF_BAD_COCORO_SPHIA"];	// RSET	SR_BAD_COCORO_SPHIA,LF_BAD_COCORO_SPHIA
    RegData["SR_BAD_COCORO_LIN_1"]	= RegData["LF_BAD_COCORO_LIN_1"];	// RSET	SR_BAD_COCORO_LIN_1,LF_BAD_COCORO_LIN_1
    RegData["SR_BAD_COCORO_YOMOGI"]	= RegData["LF_BAD_COCORO_YOMOGI"];	// RSET	SR_BAD_COCORO_YOMOGI,LF_BAD_COCORO_YOMOGI
    RegData["SR_BAD_COCORO_LIN_2"]	= RegData["LF_BAD_COCORO_LIN_2"];	// RSET	SR_BAD_COCORO_LIN_2,LF_BAD_COCORO_LIN_2
    RegData["SR_BAD_COCORO_LIN_3"]	= RegData["LF_BAD_COCORO_LIN_3"];	// RSET	SR_BAD_COCORO_LIN_3,LF_BAD_COCORO_LIN_3
    RegData["SR_BAD_COCORO_AKEKURA"]	= RegData["LF_BAD_COCORO_AKEKURA"];	// RSET	SR_BAD_COCORO_AKEKURA,LF_BAD_COCORO_AKEKURA
    RegData["SR_BAD_COCORO_TOUSI_COCORO"]	= RegData["LF_BAD_COCORO_TOUSI_COCORO"];	// RSET	SR_BAD_COCORO_TOUSI_COCORO,LF_BAD_COCORO_TOUSI_COCORO
    RegData["SR_BAD_COCORO_UNI"]	= RegData["LF_BAD_COCORO_UNI"];	// RSET	SR_BAD_COCORO_UNI,LF_BAD_COCORO_UNI
    RegData["SR_BAD_COCORO_7A"]	= RegData["LF_BAD_COCORO_7A"];	// RSET	SR_BAD_COCORO_7A,LF_BAD_COCORO_7A
    RegData["SR_BAD_COCORO_7B"]	= RegData["LF_BAD_COCORO_7B"];	// RSET	SR_BAD_COCORO_7B,LF_BAD_COCORO_7B
    RegData["SR_BAD_SATORU_BAD"]	= RegData["LF_BAD_SATORU_BAD"];	// RSET	SR_BAD_SATORU_BAD,LF_BAD_SATORU_BAD
    RegData["SR_BAD_SATORU_MIZU"]	= RegData["LF_BAD_SATORU_MIZU"];	// RSET	SR_BAD_SATORU_MIZU,LF_BAD_SATORU_MIZU
    RegData["SR_BAD_SATORU_YUBI"]	= RegData["LF_BAD_SATORU_YUBI"];	// RSET	SR_BAD_SATORU_YUBI,LF_BAD_SATORU_YUBI
    RegData["SR_BAD_SATORU_ROLLBAD"]	= RegData["LF_BAD_SATORU_ROLLBAD"];	// RSET	SR_BAD_SATORU_ROLLBAD,LF_BAD_SATORU_ROLLBAD
    RegData["SR_END_SATORU_EP"]	= RegData["LR_END_SATORU_EP"];	// RSET	SR_END_SATORU_EP,LR_END_SATORU_EP
    if(RegData["LR_CHAPTER"] == 0){	//_IF		LR_CHAPTER,C_EQ,0
	if(RegData["LF_BAD_SATORU_BAD"] == 1){	//_IF		LF_BAD_SATORU_BAD,C_EQ,1
	    if(RegData["LR_SHORTCUT_CO"] > 4){//_IF		LR_SHORTCUT_CO,C_GT,4
		RegData["LR_SHORTCUT_CO"]	= 4;	//RSET	LR_SHORTCUT_CO,4
	    }//_ENDIF
	}//	_ENDIF
	if(RegData["LF_BAD_SATORU_MIZU"] == 1){	//_IF		LF_BAD_SATORU_MIZU,C_EQ,1
	    if(RegData["LR_SHORTCUT_CO"] > 7){	//_IF		LR_SHORTCUT_CO,C_GT,7
		RegData["LR_SHORTCUT_CO"] = 7;	//RSET	LR_SHORTCUT_CO,7
	    }//				_ENDIF
	}//_ENDIF
	if(RegData["LF_BAD_SATORU_YUBI"] == 1){	//_IF		LF_BAD_SATORU_YUBI,C_EQ,1
	    if(RegData["LF_SATORU_HANNIN"] == 1){	//_IF		LF_SATORU_HANNIN,C_EQ,1
		if(RegData["LR_SHORTCUT_CO"] > 10){	//_IF		LR_SHORTCUT_CO,C_GT,10
		    RegData["LR_SHORTCUT_CO"] = 10;	//RSET	LR_SHORTCUT_CO,10
		}	//_ENDIF
	    }
	    else {	//_ELSE
		if(RegData["LR_SHORTCUT_CO"] > 12){	//_IF		LR_SHORTCUT_CO,C_GT,12
		    RegData["LR_SHORTCUT_CO"] = 12;	// RSET	LR_SHORTCUT_CO,12
		}	//		_ENDIF
	    }	//	_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_SATORU_ROLLBAD"] == 1){	//_IF		LF_BAD_SATORU_ROLLBAD,C_EQ,1
	    if(RegData["LR_SHORTCUT_CO"] > 13){	//_IF		LR_SHORTCUT_CO,C_GT,13
		RegData["LR_SHORTCUT_CO"] = 13;	//RSET	LR_SHORTCUT_CO,13
	    }	//_ENDIF
	}	//_ENDIF
	RegData["SR_SHORTCUT"] = RegData["LR_SHORTCUT_CO"];	//RSET	SR_SHORTCUT,LR_SHORTCUT_CO
    }else if(RegData["LR_CHAPTER"] == 1){	//		_ELSEIF		LR_CHAPTER,C_EQ,1
	if(RegData["LF_BAD_COCORO_SUIMINYAKU"] == 1){	//_IF		LF_BAD_COCORO_SUIMINYAKU,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 2){	//_IF		LR_SHORTCUT_SA,C_GT,2
		RegData["LR_SHORTCUT_SA"] = 2;	//RSET	LR_SHORTCUT_SA,2
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_SYOKUJI"] == 1){	//_IF		LF_BAD_COCORO_SYOKUJI,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 6){	//_IF		LR_SHORTCUT_SA,C_GT,6
		RegData["LR_SHORTCUT_SA"] = 6;	//RSET	LR_SHORTCUT_SA,6
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_ENOMOTO"] == 1){	//_IF		LF_BAD_COCORO_ENOMOTO,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 8){	//_IF		LR_SHORTCUT_SA,C_GT,8
		RegData["LR_SHORTCUT_SA"] = 8;	//RSET	LR_SHORTCUT_SA,8
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_SPHIA"] == 1){	//_IF		LF_BAD_COCORO_SPHIA,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 8){	//_IF		LR_SHORTCUT_SA,C_GT,8
		RegData["LR_SHORTCUT_SA"] = 8;	//RSET	LR_SHORTCUT_SA,8
	    }//				_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_LIN_1"] == 1){	//_IF		LF_BAD_COCORO_LIN_1,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 7){	//_IF		LR_SHORTCUT_SA,C_GT,7
		RegData["LR_SHORTCUT_SA"] = 7;	//RSET	LR_SHORTCUT_SA,7
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_YOMOGI"] == 1){	//_IF		LF_BAD_COCORO_YOMOGI,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 9){	//_IF		LR_SHORTCUT_SA,C_GT,9
		RegData["LR_SHORTCUT_SA"] = 9;	//RSET	LR_SHORTCUT_SA,9
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_LIN_2"] == 1){	//_IF		LF_BAD_COCORO_LIN_2,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 9){	//_IF		LR_SHORTCUT_SA,C_GT,9
		RegData["LR_SHORTCUT_SA"] = 9;//RSET	LR_SHORTCUT_SA,9
	    }	//				_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_LIN_3"] == 1){	//_IF		LF_BAD_COCORO_LIN_3,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 10){	//_IF		LR_SHORTCUT_SA,C_GT,10
		RegData["LR_SHORTCUT_SA"] = 10;	//RSET	LR_SHORTCUT_SA,10
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_AKEKURA"] == 1){	//_IF		LF_BAD_COCORO_AKEKURA,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 10){	//_IF		LR_SHORTCUT_SA,C_GT,10
		RegData["LR_SHORTCUT_SA"] = 10;	//RSET	LR_SHORTCUT_SA,10
	    }	//				_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_TOUSI_COCORO"] == 1){	//_IF		LF_BAD_COCORO_TOUSI_COCORO,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 10){	//_IF		LR_SHORTCUT_SA,C_GT,10
		RegData["LR_SHORTCUT_SA"] = 10;	//RSET	LR_SHORTCUT_SA,10
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_UNI"] == 1){	//_IF		LF_BAD_COCORO_UNI,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 10){	//_IF		LR_SHORTCUT_SA,C_GT,10
		RegData["LR_SHORTCUT_SA"] = 10;	//RSET	LR_SHORTCUT_SA,10
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_7A"] == 1){	//_IF		LF_BAD_COCORO_7A,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 13){	//_IF		LR_SHORTCUT_SA,C_GT,13
		RegData["LR_SHORTCUT_SA"] = 13;	//RSET	LR_SHORTCUT_SA,13
	    }	//_ENDIF
	}	//_ENDIF
	if(RegData["LF_BAD_COCORO_7B"] == 1){	//_IF		LF_BAD_COCORO_7B,C_EQ,1
	    if(RegData["LR_SHORTCUT_SA"] > 13){	//_IF		LR_SHORTCUT_SA,C_GT,13
		RegData["LR_SHORTCUT_SA"] = 13;//RSET	LR_SHORTCUT_SA,13
	    }	//_ENDIF
	}	//_ENDIF
	RegData["SR_SHORTCUT"] = RegData["LR_SHORTCUT_SA"];	//RSET	SR_SHORTCUT,LR_SHORTCUT_SA
    }	//		_ELSE
    else{
	RegData["SR_SHORTCUT"] = 15;	//RSET	SR_SHORTCUT,15
    }	//		_ENDIF

    if(RegData["SR_ED_COUNT"] < 10){
	RegData["SR_ED_COUNT"] ++;	//RADD	SR_ED_COUNT, 1
    }
    else{
	TipsFlag[88]	= 1;
    }
/*
		IF_SMALL	SR_ED_COUNT, 10, ED_COUNT2
ED_COUNT1:
		TIPS_FLG	88
		GOTO	ED_COUNT
ED_COUNT2:
		RADD	SR_ED_COUNT, 1
ED_COUNT:
*/
    if(false){	// 全メッセージクリア	//MES_CHK		LR_M00
	RegData["LR_M00"]	= 1;
    }
    else{
	RegData["LR_M00"]	= 0;
    }
    if(RegData["LR_M00"] == 0){		//IF_ZERO		LR_M00,ED_OMAKE
	
    }
    else{
/*
// 全キャラクター表情集あける！あとで！
	CGFlag[_data[0].toLowerCase()]	= 1;
		BG_FLG		REME01
		BG_FLG		REME02
		BG_FLG		REME03
		BG_FLG		REME04
		BG_FLG		REME05
		BG_FLG		REME06
		BG_FLG		REME07
		BG_FLG		REME08
		BG_FLG		REME09
		BG_FLG		REME10
		BG_FLG		REME11
		BG_FLG		REME12
		BG_FLG		REME13
		BG_FLG		REME14
		BG_FLG		REME15
		BG_FLG		REME16
		BG_FLG		REME17
		BG_FLG		REME18
		BG_FLG		REME19
		BG_FLG		REME20
		BG_FLG		REME21
		BG_FLG		REME22
		BG_FLG		REME23
		BG_FLG		REME24
		BG_FLG		REME25
		BG_FLG		REME26
		BG_FLG		REME27
		BG_FLG		REME28
		BG_FLG		REME29
		BG_FLG		REME30
		BG_FLG		REME31
		BG_FLG		REME32
		BG_FLG		REME33
		BG_FLG		REME34
		BG_FLG		REME35
*/
	if(RegData["SF_MES_MAX"] == 0){
	    RegData["SF_MES_MAX"] = 1;
	}
    }
/*
		IF_NOTZERO	SF_MES_MAX,ED_OMAKE
		DIS_KEY
//		SYS_WIND		"ロック解除――アルバム（全キャラクター表情集）"
		RSET		SF_MES_MAX,1
		ENA_KEY
ED_OMAKE:
		ENDM
*/
	delete	_data;
}